version: '3'

services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    volumes:
      - data:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

volumes:
  data:
