version: '3'

services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    volumes:
      - /tank/docker/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
